// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreatePOC(arg1) {
  return window['go']['main']['App']['CreatePOC'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeletePOC(arg1) {
  return window['go']['main']['App']['DeletePOC'](arg1);
}

export function ExportPOC(arg1) {
  return window['go']['main']['App']['ExportPOC'](arg1);
}

export function GetAllPOCs() {
  return window['go']['main']['App']['GetAllPOCs']();
}

export function GetAllScans() {
  return window['go']['main']['App']['GetAllScans']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCategoriesWithCount() {
  return window['go']['main']['App']['GetCategoriesWithCount']();
}

export function GetPOCByID(arg1) {
  return window['go']['main']['App']['GetPOCByID'](arg1);
}

export function GetPOCCount() {
  return window['go']['main']['App']['GetPOCCount']();
}

export function GetPOCsByCategory(arg1) {
  return window['go']['main']['App']['GetPOCsByCategory'](arg1);
}

export function GetPOCsBySeverity(arg1) {
  return window['go']['main']['App']['GetPOCsBySeverity'](arg1);
}

export function GetPOCsPaginated(arg1, arg2) {
  return window['go']['main']['App']['GetPOCsPaginated'](arg1, arg2);
}

export function GetScanResults(arg1) {
  return window['go']['main']['App']['GetScanResults'](arg1);
}

export function GetScanStatus(arg1) {
  return window['go']['main']['App']['GetScanStatus'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTemplatesDir() {
  return window['go']['main']['App']['GetTemplatesDir']();
}

export function ImportPOC(arg1) {
  return window['go']['main']['App']['ImportPOC'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function ReloadTemplates(arg1) {
  return window['go']['main']['App']['ReloadTemplates'](arg1);
}

export function RenameCategory(arg1, arg2) {
  return window['go']['main']['App']['RenameCategory'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchPOCs(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchPOCs'](arg1, arg2, arg3);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function StopScan(arg1) {
  return window['go']['main']['App']['StopScan'](arg1);
}

export function UpdatePOC(arg1) {
  return window['go']['main']['App']['UpdatePOC'](arg1);
}

export function ValidatePOCYAML(arg1) {
  return window['go']['main']['App']['ValidatePOCYAML'](arg1);
}
