// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateCategory(arg1:string):Promise<void>;

export function CreatePOC(arg1:models.POCTemplate):Promise<void>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeletePOC(arg1:string):Promise<void>;

export function ExportPOC(arg1:string):Promise<string>;

export function GetAllPOCs():Promise<Array<models.POCTemplate>>;

export function GetAllScans():Promise<Array<models.ScanStatus>>;

export function GetCategories():Promise<Array<string>>;

export function GetCategoriesWithCount():Promise<Record<string, number>>;

export function GetPOCByID(arg1:string):Promise<models.POCTemplate>;

export function GetPOCCount():Promise<number>;

export function GetPOCsByCategory(arg1:string):Promise<Array<models.POCTemplate>>;

export function GetPOCsBySeverity(arg1:string):Promise<Array<models.POCTemplate>>;

export function GetPOCsPaginated(arg1:number,arg2:number):Promise<Record<string, any>>;

export function GetScanResults(arg1:string):Promise<Array<models.ScanResult>>;

export function GetScanStatus(arg1:string):Promise<models.ScanStatus>;

export function GetStats():Promise<models.Stats>;

export function GetTemplatesDir():Promise<string>;

export function ImportPOC(arg1:string):Promise<models.POCTemplate>;

export function LoadSettings():Promise<models.Settings>;

export function ReloadTemplates(arg1:string):Promise<void>;

export function RenameCategory(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:models.Settings):Promise<void>;

export function SearchPOCs(arg1:string,arg2:string,arg3:string):Promise<Array<models.POCTemplate>>;

export function StartScan(arg1:models.ScanRequest):Promise<string>;

export function StopScan(arg1:string):Promise<void>;

export function UpdatePOC(arg1:models.POCTemplate):Promise<void>;

export function ValidatePOCYAML(arg1:string):Promise<void>;
